codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 1 # number of decimal places
  round: down # round down coverage
  range: "70...100" # visual color range in codecov
  status:
    project: yes # measures the overall project coverage and compares it against the base of the pull request or parent commit
    patch: # measures only the lines adjusted in the pull request or single commit, if the commit is not in a pull request
      default:
        target: 100% # all new code should have 100% coverage
    changes: yes # detect changes in coverage that are NOT included in the commit/pull diff, and report these changes as a commit status

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment: # configure github pull request comment
  layout: "diff, flags, files"
  behavior: default # update comment, if exists. Otherwise post new.
  require_changes: no # comments post regardless if there is a coverage change or not

ignore: # ignore these files when measuring absolute coverage (reported in the Github badge)
  - "Pods/"
  - "Sources/Shuffle/Internal"
  - "Tests/"
