language: objective-c
os: osx
osx_image: xcode12.2
jobs:
  include:
    stage: "Build & Test"
      script: xcodebuild -workspace Shuffle.xcworkspace -scheme SwiftLint -sdk iphonesimulator -destination platform="iOS Simulator,name=iPhone 11 Pro Max,OS=14.4"
          name: "Run SwiftLint"
      script: xcodebuild test -workspace Shuffle.xcworkspace -scheme ShuffleTests -sdk iphonesimulator -destination platform="iOS Simulator,name=iPhone 11 Pro Max,OS=14.4"
          name: "Run Unit Tests"
      script: xcodebuild -workspace Shuffle.xcworkspace -scheme ShuffleExample -sdk iphonesimulator -destination platform="iOS Simulator,name=iPhone 11 Pro Max,OS=14.4"
        name: "Build Example Project"

# upload codecov report
after_success: bash <(curl -s https://codecov.io/bash) -J 'Shuffle'
